stages:
  - test
  - deploy

test_job:
  stage: test
  script:
    - ./mvnw test
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml

deploy_job:
  stage: deploy
  script:
    - ./mvnw package -Pnative -Dquarkus.native.container-build=true